apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapidocker-deployment
  labels:
    app: webapidocker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapidocker
  template:
    metadata:
      labels:
        app: webapidocker
    spec:
      containers:
        - name: webapidocker
          image: prathamacrassignment.azurecr.io/webapidocker:latest
          ports:
            - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: webapidocker-service
spec:
  type: LoadBalancer
  selector:
    app: webapidocker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
